/*
 * NetbeansView.java
 *
 * Created on 12. Juni 2008, 17:31
 */

package org.jens.fotoBrowser.client;

/**
 *
 * @author  hacker
 */
public class NetbeansView extends javax.swing.JFrame {

    /** Creates new form NetbeansView */
    public NetbeansView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnDeleteThis = new javax.swing.JMenuItem();
        mntCheckAutoResize2 = new javax.swing.JCheckBoxMenuItem();
        framePreferences = new javax.swing.JFrame();
        labelHeight = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        labelWidth = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        checkManualSize = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        comboSized = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        checkWantAutoResizeAsSaved = new javax.swing.JCheckBox();
        dlgUpload = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelPreview = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        txtUpload = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listThumbs = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        panelmageBackground = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        checkResize = new javax.swing.JCheckBox();
        btnSaveAs = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDeleteThis = new javax.swing.JButton();
        separatorCheckboxes = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        mnSaveAll = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        mnShowPreferences = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mntCheckAutoResize = new javax.swing.JCheckBoxMenuItem();
        mntReload = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        mnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jens/fotoBrowser/images/16x16/actions/document-save.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jens/fotoBrowser/client/i18n"); // NOI18N
        mnSaveAs.setText(bundle.getString("Save_As")); // NOI18N
        mnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveAsActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnSaveAs);
        jPopupMenu1.add(jSeparator2);

        mnDeleteThis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jens/fotoBrowser/images/16x16/actions/edit-delete.png"))); // NOI18N
        mnDeleteThis.setText(bundle.getString("Delete_this")); // NOI18N
        mnDeleteThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteThisActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnDeleteThis);

        mntCheckAutoResize2.setSelected(true);
        mntCheckAutoResize2.setText(bundle.getString("Auto_Resize")); // NOI18N
        mntCheckAutoResize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntCheckAutoResize2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mntCheckAutoResize2);

        framePreferences.setTitle(bundle.getString("Preferences")); // NOI18N

        labelHeight.setText(bundle.getString("Height")); // NOI18N
        labelHeight.setEnabled(false);

        txtWidth.setText("1024");
        txtWidth.setEnabled(false);

        labelWidth.setText(bundle.getString("Width")); // NOI18N
        labelWidth.setEnabled(false);

        txtHeight.setText("800");
        txtHeight.setEnabled(false);

        checkManualSize.setText(bundle.getString("Manual_Size")); // NOI18N
        checkManualSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkManualSizeActionPerformed(evt);
            }
        });

        jLabel3.setText(bundle.getString("Exported_Image_Size")); // NOI18N

        comboSized.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1280x1024", "macbook", "1024x800" }));
        comboSized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSizedActionPerformed(evt);
            }
        });

        jButton1.setText(bundle.getString("OK")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkWantAutoResizeAsSaved.setSelected(true);
        checkWantAutoResizeAsSaved.setText(bundle.getString("Auto_Resize")); // NOI18N
        checkWantAutoResizeAsSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWantAutoResizeAsSavedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout framePreferencesLayout = new javax.swing.GroupLayout(framePreferences.getContentPane());
        framePreferences.getContentPane().setLayout(framePreferencesLayout);
        framePreferencesLayout.setHorizontalGroup(
            framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePreferencesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framePreferencesLayout.createSequentialGroup()
                        .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboSized, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(framePreferencesLayout.createSequentialGroup()
                                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelWidth)
                                    .addComponent(labelHeight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                            .addComponent(checkManualSize)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkWantAutoResizeAsSaved))
                .addContainerGap())
        );
        framePreferencesLayout.setVerticalGroup(
            framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePreferencesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkWantAutoResizeAsSaved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkManualSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSized, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWidth)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel1.setText(bundle.getString("Title")); // NOI18N

        btnSave.setText(bundle.getString("Save")); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText(bundle.getString("Cancel")); // NOI18N
        btnCancel.setDefaultCapable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        dlgUpload.getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        labelPreview.setText(bundle.getString("Preview")); // NOI18N

        btnSelect.setText(bundle.getString("Select_...")); // NOI18N
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("File")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelect))
                    .addComponent(labelPreview))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect)
                    .addComponent(txtUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPreview)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        dlgUpload.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("FotoBrowser")); // NOI18N

        jSplitPane1.setDividerLocation(150);

        listThumbs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listThumbs.setComponentPopupMenu(jPopupMenu1);
        listThumbs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listThumbsValueChanged(evt);
            }
        });
        listThumbs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listThumbsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listThumbs);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        panelInfo.setLayout(new java.awt.BorderLayout());

        labelName.setText("XXXX");
        panelInfo.add(labelName, java.awt.BorderLayout.WEST);

        labelInfo.setText("XXX");
        panelInfo.add(labelInfo, java.awt.BorderLayout.EAST);

        txtStatus.setText("XXX");
        panelInfo.add(txtStatus, java.awt.BorderLayout.CENTER);

        jPanel2.add(panelInfo, java.awt.BorderLayout.NORTH);

        panelmageBackground.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelmageBackground, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        toolbar.setRollover(true);

        checkResize.setText(bundle.getString("Auto_Resize")); // NOI18N
        checkResize.setFocusable(false);
        checkResize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkResize.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        checkResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkResizeActionPerformed(evt);
            }
        });
        toolbar.add(checkResize);

        btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jens/fotoBrowser/images/16x16/actions/document-save.png"))); // NOI18N
        btnSaveAs.setText(bundle.getString("Save_As_...")); // NOI18N
        btnSaveAs.setFocusable(false);
        btnSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });
        toolbar.add(btnSaveAs);
        toolbar.add(jSeparator1);

        btnDeleteThis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jens/fotoBrowser/images/16x16/actions/edit-delete.png"))); // NOI18N
        btnDeleteThis.setText(bundle.getString("Delete_this")); // NOI18N
        btnDeleteThis.setFocusable(false);
        btnDeleteThis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteThis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteThisActionPerformed(evt);
            }
        });
        toolbar.add(btnDeleteThis);
        toolbar.add(separatorCheckboxes);
        toolbar.add(jSeparator4);

        getContentPane().add(toolbar, java.awt.BorderLayout.NORTH);

        fileMenu.setText(bundle.getString("File")); // NOI18N

        openMenuItem.setText(bundle.getString("Upload")); // NOI18N
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setText(bundle.getString("Save")); // NOI18N
        saveMenuItem.setEnabled(false);
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText(bundle.getString("Save_As_...")); // NOI18N
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        mnSaveAll.setText(bundle.getString("Save_all")); // NOI18N
        mnSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveAllActionPerformed(evt);
            }
        });
        fileMenu.add(mnSaveAll);

        exitMenuItem.setText(bundle.getString("Exit")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText(bundle.getString("Edit")); // NOI18N

        cutMenuItem.setText(bundle.getString("Cut")); // NOI18N
        cutMenuItem.setEnabled(false);
        editMenu.add(cutMenuItem);

        copyMenuItem.setText(bundle.getString("Copy")); // NOI18N
        copyMenuItem.setEnabled(false);
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText(bundle.getString("Paste")); // NOI18N
        pasteMenuItem.setEnabled(false);
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText(bundle.getString("Delete")); // NOI18N
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        mnShowPreferences.setText(bundle.getString("Preferences")); // NOI18N
        mnShowPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShowPreferencesActionPerformed(evt);
            }
        });
        editMenu.add(mnShowPreferences);

        menuBar.add(editMenu);

        jMenu1.setText(bundle.getString("View")); // NOI18N

        mntCheckAutoResize.setSelected(true);
        mntCheckAutoResize.setText(bundle.getString("Auto_Resize")); // NOI18N
        mntCheckAutoResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntCheckAutoResizeActionPerformed(evt);
            }
        });
        jMenu1.add(mntCheckAutoResize);

        mntReload.setText(bundle.getString("Reload")); // NOI18N
        mntReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntReloadActionPerformed(evt);
            }
        });
        jMenu1.add(mntReload);

        menuBar.add(jMenu1);

        helpMenu.setText(bundle.getString("Help")); // NOI18N
        helpMenu.setEnabled(false);

        contentsMenuItem.setText(bundle.getString("Contents")); // NOI18N
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText(bundle.getString("About")); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

private void listThumbsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listThumbsValueChanged
        onChangeListItem(evt);
}//GEN-LAST:event_listThumbsValueChanged

private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
    doSaveAs();
}//GEN-LAST:event_btnSaveAsActionPerformed

private void btnDeleteThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteThisActionPerformed
    doDeleteThis();
}//GEN-LAST:event_btnDeleteThisActionPerformed

private void mnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveAsActionPerformed
    doSaveAs();
}//GEN-LAST:event_mnSaveAsActionPerformed

private void mnDeleteThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteThisActionPerformed
    doDeleteThis();
}//GEN-LAST:event_mnDeleteThisActionPerformed

private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
    doSaveAs();
}//GEN-LAST:event_saveAsMenuItemActionPerformed

private void checkManualSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkManualSizeActionPerformed
    togglePreferencesVisibility();
}//GEN-LAST:event_checkManualSizeActionPerformed

private void comboSizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSizedActionPerformed
    updateOutputSize();
}//GEN-LAST:event_comboSizedActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    updateOutputSize();
    framePreferences.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void mnShowPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShowPreferencesActionPerformed
    framePreferences.setVisible(true);
    framePreferences.pack();
}//GEN-LAST:event_mnShowPreferencesActionPerformed

private void checkWantAutoResizeAsSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWantAutoResizeAsSavedActionPerformed
    toggleAllPref();
}//GEN-LAST:event_checkWantAutoResizeAsSavedActionPerformed

private void listThumbsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listThumbsKeyPressed
    panelImageUserMakesABlip(evt);
}//GEN-LAST:event_listThumbsKeyPressed

private void checkResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkResizeActionPerformed
    onToggleResize(checkResize.getModel().isSelected());
}//GEN-LAST:event_checkResizeActionPerformed

private void mntCheckAutoResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntCheckAutoResizeActionPerformed
    onToggleResize(mntCheckAutoResize.getModel().isSelected());
}//GEN-LAST:event_mntCheckAutoResizeActionPerformed

private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
    doDeleteThis();
}//GEN-LAST:event_deleteMenuItemActionPerformed

private void mntCheckAutoResize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntCheckAutoResize2ActionPerformed
    onToggleResize(mntCheckAutoResize2.getModel().isSelected());
}//GEN-LAST:event_mntCheckAutoResize2ActionPerformed

private void mntReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntReloadActionPerformed
    doReload();
}//GEN-LAST:event_mntReloadActionPerformed

private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
    doUpload();
}//GEN-LAST:event_openMenuItemActionPerformed

private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
    doSelectUploadFile();
}//GEN-LAST:event_btnSelectActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    dlgUpload.setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    doUploadDone();
}//GEN-LAST:event_btnSaveActionPerformed

private void mnSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveAllActionPerformed
    doSaveAll();
}//GEN-LAST:event_mnSaveAllActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetbeansView().setVisible(true);
            }
        });
    }

    protected void onChangeListItem(javax.swing.event.ListSelectionEvent evt) {
        throw new UnknownError();
    }

    protected void doSaveAs() {
        throw new UnknownError();
    }

    protected void doDeleteThis() {
        throw new UnknownError();
    }

    protected void onToggleResize(boolean value) {
        throw new UnknownError();
    }

    protected void updateOutputSize() {
        throw new UnknownError();
    }

    protected void panelImageUserMakesABlip(java.awt.event.KeyEvent evt) {
        throw new UnknownError();
    }

    protected void doReload() {
        throw new UnknownError();
    }

    protected void doUpload() {
        throw new UnknownError();
    }

    protected void doUploadDone() {
         throw new UnknownError();
    }

    protected void doSelectUploadFile() {
        throw new UnknownError();
    }

    protected void doSaveAll() {
        throw new UnknownError();
    }

    protected void togglePreferencesVisibility() {
        labelHeight.setEnabled(checkManualSize.isSelected());
        labelWidth.setEnabled(checkManualSize.isSelected());
        txtHeight.setEnabled(checkManualSize.isSelected());
        txtWidth.setEnabled(checkManualSize.isSelected());
        comboSized.setEnabled(!checkManualSize.isSelected());
    }

    protected void toggleAllPref() {
        checkManualSize.setEnabled(checkWantAutoResizeAsSaved.getModel().isSelected());
        if (checkWantAutoResizeAsSaved.getModel().isSelected()) {
            togglePreferencesVisibility();
        } else {
            // All Disable !
            labelHeight.setEnabled(false);
            labelWidth.setEnabled(false);
            txtHeight.setEnabled(false);
            txtWidth.setEnabled(false);
            comboSized.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuItem aboutMenuItem;
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnDeleteThis;
    protected javax.swing.JButton btnSave;
    protected javax.swing.JButton btnSaveAs;
    protected javax.swing.JButton btnSelect;
    protected javax.swing.JCheckBox checkManualSize;
    protected javax.swing.JCheckBox checkResize;
    protected javax.swing.JCheckBox checkWantAutoResizeAsSaved;
    protected javax.swing.JComboBox comboSized;
    protected javax.swing.JMenuItem contentsMenuItem;
    protected javax.swing.JMenuItem copyMenuItem;
    protected javax.swing.JMenuItem cutMenuItem;
    protected javax.swing.JMenuItem deleteMenuItem;
    protected javax.swing.JDialog dlgUpload;
    protected javax.swing.JMenu editMenu;
    protected javax.swing.JMenuItem exitMenuItem;
    protected javax.swing.JMenu fileMenu;
    protected javax.swing.JFrame framePreferences;
    protected javax.swing.JMenu helpMenu;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JMenu jMenu1;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JPopupMenu jPopupMenu1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToolBar.Separator jSeparator1;
    protected javax.swing.JSeparator jSeparator2;
    protected javax.swing.JToolBar.Separator jSeparator4;
    protected javax.swing.JSplitPane jSplitPane1;
    protected javax.swing.JLabel labelHeight;
    protected javax.swing.JLabel labelInfo;
    protected javax.swing.JLabel labelName;
    protected javax.swing.JLabel labelPreview;
    protected javax.swing.JLabel labelWidth;
    protected javax.swing.JList listThumbs;
    protected javax.swing.JMenuBar menuBar;
    protected javax.swing.JMenuItem mnDeleteThis;
    protected javax.swing.JMenuItem mnSaveAll;
    protected javax.swing.JMenuItem mnSaveAs;
    protected javax.swing.JMenuItem mnShowPreferences;
    protected javax.swing.JCheckBoxMenuItem mntCheckAutoResize;
    protected javax.swing.JCheckBoxMenuItem mntCheckAutoResize2;
    protected javax.swing.JMenuItem mntReload;
    protected javax.swing.JMenuItem openMenuItem;
    protected javax.swing.JPanel panelInfo;
    protected javax.swing.JPanel panelmageBackground;
    protected javax.swing.JMenuItem pasteMenuItem;
    protected javax.swing.JMenuItem saveAsMenuItem;
    protected javax.swing.JMenuItem saveMenuItem;
    protected javax.swing.JToolBar.Separator separatorCheckboxes;
    protected javax.swing.JToolBar toolbar;
    protected javax.swing.JTextField txtHeight;
    protected javax.swing.JLabel txtStatus;
    protected javax.swing.JTextField txtTitle;
    protected javax.swing.JTextField txtUpload;
    protected javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

}
